name: connevents
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  ticketview: ^1.0.0
  rflutter_alert: ^2.0.4
  select_form_field: ^2.2.0
  table_calendar: ^3.0.2
  percent_indicator: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  http:
  location:
  json_annotation: ^4.3.0
  fluttertoast: ^8.0.8
  dio: ^4.0.1
  hive:
  hive_flutter:
  hive_generator:
  pretty_dio_logger: ^1.1.1
  retrofit: ^2.0.1
  shared_preferences:
  google_sign_in: ^5.0.4
  firebase_auth: ^3.1.2
  #flutter_login_facebook: ^1.1.0
  flutter_facebook_auth: ^3.5.2
  stripe_payment:
  flutter_credit_card: ^3.0.1
  image_picker: ^0.8.2
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.4
  #date_time_picker: ^2.1.0
  date_format: ^2.0.4
  analyzer: ^2.6.0
  places_service: ^0.1.0+2
  file_picker: ^4.3.1
  multi_image_picker2: ^5.0.2
  google_maps_flutter: ^2.0.11
  pull_to_refresh: ^2.0.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  better_player: ^0.0.77
  flutter_polyline_points: ^1.0.0
  screenshot: ^1.2.3
  printing: ^5.6.6
  syncfusion_flutter_barcodes: ^19.4.41
  qr_code_scanner: ^0.6.1
  barcode_scan2: ^4.2.0
  onesignal_flutter: ^3.2.7
  social_share: ^2.2.1
  flutter_sms: ^2.3.2
  contacts_service: ^0.6.3
  permission_handler: ^8.3.0
  provider: ^6.0.2
  agora_rtc_engine: ^4.2.0
  agora_rtm: ^1.1.0
  uuid: ^3.0.5
  url_launcher: ^6.0.18
  image_gallery_saver: ^1.7.1
  in_app_purchase: ^2.0.1
  pay: ^1.0.6
  connectivity_plus: ^2.2.0
  internet_connection_checker: ^0.0.1+3
  webview_flutter: ^3.0.0
  emoji_picker_flutter: ^1.1.1
  video_player: ^2.2.14
  csv: ^5.0.1
  video_compress: ^3.1.0
  image_cropper: ^1.5.0
  flutter_native_splash: ^1.3.2
  flutter_downloader: ^1.7.2
  custom_image_crop: ^0.0.4
  http_auth: ^1.0.1
  getwidget: ^2.0.5
  camera: ^0.9.4+19
  external_path: ^1.0.1
  purchases_flutter: ^3.10.0
  downloads_path_provider_28:
  flutter_icons: ^1.1.0
  firebase_dynamic_links: ^3.0.2
  get:
  # change_app_package_name: ^1.0.0
  # google_sign_in: "^4.5.1"


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  retrofit_generator: ^2.0.1+2
  json_serializable:


flutter_native_splash:
  color: "#000000"
  image: assets/splash.png
  android: true
  ios: true


#dependency_overrides:
 # analyzer: 0.39.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/icons/tabs/
    - assets/

    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
