name: connevents
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.1.1
  ticketview: ^1.0.0
  percent_indicator: 3.4.0
  sliding_up_panel: ^2.0.0+1
  http: ^0.13.4
  json_annotation: ^4.5.0
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.20
  #flutter_login_facebook: ^1.1.0
  flutter_facebook_auth: 3.5.7
  stripe_payment: ^1.1.4
  flutter_credit_card: ^3.0.1
  image_picker: 0.8.4+11
  video_thumbnail: ^0.5.0
  path_provider: ^2.0.11
  #date_time_picker: ^2.1.0
  date_format: ^2.0.6
  #analyzer: ^2.6.0
  places_service: ^0.1.2
  file_picker: ^4.6.1
  multi_image_picker2: ^5.0.2
  google_maps_flutter: ^2.1.8
  pull_to_refresh: ^2.0.0
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  better_player: ^0.0.80
  flutter_polyline_points: ^1.0.0
  screenshot: ^1.2.3
  printing: ^5.9.1
  syncfusion_flutter_barcodes: ^20.1.60
  qr_code_scanner: 0.7.0
  barcode_scan2: ^4.2.1
  onesignal_flutter: ^3.3.2
  social_share: ^2.2.1
  flutter_sms: ^2.3.3
  contacts_service: ^0.6.3
  permission_handler: 9.0.1
  provider: ^6.0.3
  agora_rtc_engine: ^4.2.2
  agora_rtm: ^1.1.1
  uuid: ^3.0.6
  url_launcher: ^6.1.3
  image_gallery_saver: ^1.7.1
  in_app_purchase: ^3.0.6
  pay: ^1.0.10
  connectivity_plus: ^2.3.4
  internet_connection_checker: ^0.0.1+3
  webview_flutter: ^3.0.4
  emoji_picker_flutter: 1.2.1
  video_player: ^2.4.5
  csv: ^5.0.1
  video_compress: ^3.1.0
  image_cropper: ^2.0.3
  flutter_native_splash: ^2.1.6
  flutter_downloader: ^1.7.4
  http_auth: ^1.0.1
  camera: 0.9.4+15
  external_path: ^1.0.1
  downloads_path_provider_28: ^0.1.2
  flutter_icons: ^1.1.0
  firebase_dynamic_links: ^4.2.6
  get: ^4.6.5
  # change_app_package_name: ^1.0.0
  # google_sign_in: ^5.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0


flutter_native_splash:
  color: "#000000"
  image: assets/splash.png
  android: true
  ios: true


#dependency_overrides:
 # analyzer: 0.39.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/icons/tabs/
    - assets/

    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
